### ISSUE TITLE
你好，我直接yarn会报错

### ISSUE THREAD

**Issue by rookiewxy** [ltaoo/easy-icons#3]

**Comment by rookiewxy** [comment]
这个地址我下载本地运行 https://stackblitz.com/edit/react-ts-icons?file=icons%2Findex.ts

**Comment by rookiewxy** [comment]
我刚刚换了一个版本可以运行这个命令yarn ei gen all --svg src/svg --output src/icons，但是没有生成icons文件夹，并报错，提示没有找到\icons\asn

**Comment by ltaoo** [comment]
hi，非常抱歉我在 `1.0.0` 版本把命令行去掉了，建议使用 `1.0.0` 版本暴露的方法来生成 `icons`，更加简单。

```js
const path = require("path");

const { reactIconsGeneratorFromSVGDir } = require("easy-icons");

const SVG_DIR = path.resolve(__dirname, "../public/svg");
const ICON_OUTPUT_DIR = path.resolve(__dirname, "../src/icons");

reactIconsGeneratorFromSVGDir({
  // SVG 文件夹
  entry: SVG_DIR,
  // icons 文件夹路径
  output: ICON_OUTPUT_DIR,
  // 是否生成 ts 文件，false 时生成 js 文件
  typescript: true,
});
```

https://github.com/ltaoo/easy-icons-example/tree/master  示例项目也更新了，可以再试试看。 😂

**Comment by rookiewxy** [comment]
好的，谢谢，我现在使用的是1.0.0但是asn文件夹下没有内容是空的，没有报错

**Comment by rookiewxy** [comment]
嗯嗯，试了最新版，但是asn文件夹下面是空的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月10日(星期五) 晚上8:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ltaoo/easy-icons] 你好，我直接yarn会报错 (#3)





 
hi，非常抱歉我在 1.0.0 版本把命令行去掉了，建议使用 1.0.0 版本暴露的方法来生成 icons，更加简单。
 const path = require("path"); const { reactIconsGeneratorFromSVGDir } = require("easy-icons"); const SVG_DIR = path.resolve(__dirname, "../public/svg"); const ICON_OUTPUT_DIR = path.resolve(__dirname, "../src/icons"); reactIconsGeneratorFromSVGDir({   // SVG 文件夹   entry: SVG_DIR,   // icons 文件夹路径   output: ICON_OUTPUT_DIR,   // 是否生成 ts 文件，false 时生成 js 文件   typescript: true, });
 
https://github.com/ltaoo/easy-icons-example/tree/master  示例项目也更新了，可以再试试看。 😂
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ltaoo** [comment]
resolved at v1.1.3
